# docker-compose.yml
version: '3.7'
services:
    db:
        container_name: postgres
        image: postgres:latest
        restart: always
        env_file:
            - settings/database.env
        volumes: 
            - /home/${USERNAME}/osrs-farm-platform/postgres-data:/var/lib/postgresql/data
        ports: 
            - 5432:5432
    
    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080